/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2021-06-28 12:51:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class FindPwEmail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/FinalProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/PrjApp/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1623778880000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("UTF-8");
String cp = request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns:v=\"urn:schemas-microsoft-com:vml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width; initial-scale=1.0; maximum-scale=1.0;\" />\r\n");
      out.write("<link href='https://fonts.googleapis.com/css?family=Work+Sans:300,400,500,600,700' rel=\"stylesheet\">\r\n");
      out.write("<link href='https://fonts.googleapis.com/css?family=Quicksand:300,400,700' rel=\"stylesheet\">\r\n");
      out.write("<title>FindPwEmail</title>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tbackground-color: #ffffff;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\t-webkit-font-smoothing: antialiased;\r\n");
      out.write("\tmso-margin-top-alt: 0px;\r\n");
      out.write("\tmso-margin-bottom-alt: 0px;\r\n");
      out.write("\tmso-padding-alt: 0px 0px 0px 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("p, h1, h2, h3, h4 {\r\n");
      out.write("\tmargin-top: 0;\r\n");
      out.write("\tmargin-bottom: 0;\r\n");
      out.write("\tpadding-top: 0;\r\n");
      out.write("\tpadding-bottom: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("span.preheader {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\tfont-size: 1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("html {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tborder: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ----------- responsivity ----------- */\r\n");
      out.write("@media only screen and (max-width: 640px) {\r\n");
      out.write("\t/*------ top header ------ */\r\n");
      out.write("\t.main-header {\r\n");
      out.write("\t\tfont-size: 20px !important;\r\n");
      out.write("\t}\r\n");
      out.write("\t.main-section-header {\r\n");
      out.write("\t\tfont-size: 28px !important;\r\n");
      out.write("\t}\r\n");
      out.write("\t.show {\r\n");
      out.write("\t\tdisplay: block !important;\r\n");
      out.write("\t}\r\n");
      out.write("\t.hide {\r\n");
      out.write("\t\tdisplay: none !important;\r\n");
      out.write("\t}\r\n");
      out.write("\t.align-center {\r\n");
      out.write("\t\ttext-align: center !important;\r\n");
      out.write("\t}\r\n");
      out.write("\t.no-bg {\r\n");
      out.write("\t\tbackground: none !important;\r\n");
      out.write("\t}\r\n");
      out.write("\t/*----- main image -------*/\r\n");
      out.write("\t.main-image img {\r\n");
      out.write("\t\twidth: 440px !important;\r\n");
      out.write("\t\theight: auto !important;\r\n");
      out.write("\t}\r\n");
      out.write("\t/* ====== divider ====== */\r\n");
      out.write("\t.divider img {\r\n");
      out.write("\t\twidth: 440px !important;\r\n");
      out.write("\t}\r\n");
      out.write("\t/*-------- container --------*/\r\n");
      out.write("\t.container590 {\r\n");
      out.write("\t\twidth: 440px !important;\r\n");
      out.write("\t}\r\n");
      out.write("\t.container580 {\r\n");
      out.write("\t\twidth: 400px !important;\r\n");
      out.write("\t}\r\n");
      out.write("\t.main-button {\r\n");
      out.write("\t\twidth: 220px !important;\r\n");
      out.write("\t}\r\n");
      out.write("\t/*-------- secions ----------*/\r\n");
      out.write("\t.section-img img {\r\n");
      out.write("\t\twidth: 320px !important;\r\n");
      out.write("\t\theight: auto !important;\r\n");
      out.write("\t}\r\n");
      out.write("\t.team-img img {\r\n");
      out.write("\t\twidth: 100% !important;\r\n");
      out.write("\t\theight: auto !important;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media only screen and (max-width: 479px) {\r\n");
      out.write("\t/*------ top header ------ */\r\n");
      out.write("\t.main-header {\r\n");
      out.write("\t\tfont-size: 18px !important;\r\n");
      out.write("\t}\r\n");
      out.write("\t.main-section-header {\r\n");
      out.write("\t\tfont-size: 26px !important;\r\n");
      out.write("\t}\r\n");
      out.write("\t/* ====== divider ====== */\r\n");
      out.write("\t.divider img {\r\n");
      out.write("\t\twidth: 280px !important;\r\n");
      out.write("\t}\r\n");
      out.write("\t/*-------- container --------*/\r\n");
      out.write("\t.container590 {\r\n");
      out.write("\t\twidth: 280px !important;\r\n");
      out.write("\t}\r\n");
      out.write("\t.container590 {\r\n");
      out.write("\t\twidth: 280px !important;\r\n");
      out.write("\t}\r\n");
      out.write("\t.container580 {\r\n");
      out.write("\t\twidth: 260px !important;\r\n");
      out.write("\t}\r\n");
      out.write("\t/*-------- secions ----------*/\r\n");
      out.write("\t.section-img img {\r\n");
      out.write("\t\twidth: 280px !important;\r\n");
      out.write("\t\theight: auto !important;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<!-- [if gte mso 9]><style type=”text/css”>\r\n");
      out.write("        body {\r\n");
      out.write("        font-family: arial, sans-serif!important;\r\n");
      out.write("        }\r\n");
      out.write("        </style>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"respond\" leftmargin=\"0\" topmargin=\"0\" marginwidth=\"0\"\r\n");
      out.write("\tmarginheight=\"0\">\r\n");
      out.write("\t<!-- pre-header -->\r\n");
      out.write("\t<table style=\"display: none !important;\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\tstyle=\"overflow: hidden; display: none; font-size: 1px; color: #ffffff; line-height: 1px; font-family: Arial; maxheight: 0px; max-width: 0px; opacity: 0;\">\r\n");
      out.write("\t\t\t\t\tPre-header for the newsletter template</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<!-- pre-header end -->\r\n");
      out.write("\t<!-- header -->\r\n");
      out.write("\t<table border=\"0\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\"\r\n");
      out.write("\t\tbgcolor=\"ffffff\">\r\n");
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t<table border=\"0\" align=\"center\" width=\"590\" cellpadding=\"0\"cellspacing=\"0\" class=\"container590\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"25\" style=\"font-size: 25px; line-height: 25px;\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<table border=\"0\" align=\"center\" width=\"590\" cellpadding=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\tcellspacing=\"0\" class=\"container590\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<br><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"\" style=\"display: block; border-style: none !important; border: 0 !important;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img border=\"0\" style=\"display: block; width: 100px;\" src=\"images/leggo_logo.png\" alt=\"\" /></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"25\" style=\"font-size: 25px; line-height: 25px;\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<!-- end header -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- big image section -->\r\n");
      out.write("\t<table border=\"0\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\"\r\n");
      out.write("\t\tbgcolor=\"ffffff\" class=\"bg_color\">\r\n");
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t<table border=\"0\" align=\"center\" width=\"590\" cellpadding=\"0\"\r\n");
      out.write("\t\t\t\t\tcellspacing=\"0\" class=\"container590\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\" class=\"section-img\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"\" style=\"border-style: none !important; display: block; border: 0 !important;\"></a></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"20\" style=\"font-size: 20px; line-height: 20px;\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"color: #343434; font-size: 24px; font-family: Quicksand, Calibri, sans-serif; font-weight: 700; letter-spacing: 3px; line-height: 35px;\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"main-header\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"line-height: 35px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t임시 비밀번호는 <span style=\"color: #649ef5;\">5caad2</span> 입니다.\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"10\" style=\"font-size: 10px; line-height: 10px;\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t<table border=\"0\" width=\"40\" align=\"center\" cellpadding=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\tcellspacing=\"0\" bgcolor=\"eeeeee\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td height=\"2\" style=\"font-size: 2px; line-height: 2px;\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"20\" style=\"font-size: 20px; line-height: 20px;\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t<table border=\"0\" width=\"400\" align=\"center\" cellpadding=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\tcellspacing=\"0\" class=\"container590\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td align=\"center\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"color: #888888; font-size: 16px; font-family: 'Work Sans', Calibri, sans-serif; line-height: 24px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div style=\"width: 500px; line-height: 24px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t로그인을 완료하신 뒤 비밀번호를 변경해주세요.<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t비밀번호 변경 전까지 사이트 기능을 이용하실 수 없습니다.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"25\" style=\"font-size: 25px; line-height: 25px;\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t<table border=\"0\" align=\"center\" width=\"160\" cellpadding=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\tcellspacing=\"0\" bgcolor=\"2A79EF\" style=\"border-radius: 5px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td height=\"10\" style=\"font-size: 10px; line-height: 10px;\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td align=\"center\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"color: #ffffff; font-size: 14px; font-family: 'Work Sans', Calibri, sans-serif; line-height: 26px;\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div style=\"line-height: 26px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://localhost:8090/PrjApp/Login.jsp\" style=\"color: #ffffff; text-decoration: none;\">로그인하러 가기</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td height=\"10\" style=\"font-size: 10px; line-height: 10px;\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<!-- end section -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- contact section -->\r\n");
      out.write("\t<table border=\"0\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\"\r\n");
      out.write("\t\tbgcolor=\"ffffff\" class=\"bg_color\">\r\n");
      out.write("\r\n");
      out.write("\t\t<tr class=\"hide\">\r\n");
      out.write("\t\t\t<td height=\"25\" style=\"font-size: 25px; line-height: 25px;\">&nbsp;</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td height=\"40\" style=\"font-size: 40px; line-height: 40px;\">&nbsp;</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td height=\"60\"\r\n");
      out.write("\t\t\t\tstyle=\"border-top: 1px solid #e0e0e0; font-size: 60px; line-height: 60px;\">&nbsp;</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t<table border=\"0\" align=\"center\" width=\"590\" cellpadding=\"0\"\r\n");
      out.write("\t\t\t\t\tcellspacing=\"0\" class=\"container590 bg_color\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<table border=\"0\" width=\"300\" align=\"left\" cellpadding=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\tcellspacing=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"container590\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- logo -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td align=\"left\"><a href=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"display: block; border-style: none !important; border: 0 !important;\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tborder=\"0\" style=\"display: block; width: 80px;\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsrc=\"images/leggo_logo.png\"  alt=\"\" /></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td height=\"25\" style=\"font-size: 25px; line-height: 25px;\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td align=\"left\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"color: #888888; font-size: 14px; font-family: 'Work Sans', Calibri, sans-serif; line-height: 23px;\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"text_color\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"color: #333333; font-size: 14px; font-family: 'Work Sans', Calibri, sans-serif; font-weight: 600; mso-line-height-rule: exactly; line-height: 23px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tEmail us: <br /> <a href=\"mailto:\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"color: #888888; font-size: 14px; font-family: 'Hind Siliguri', Calibri, Sans-serif; font-weight: 400;\">2021leggo@gmail.com</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<table border=\"0\" width=\"2\" align=\"left\" cellpadding=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\tcellspacing=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"container590\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td width=\"2\" height=\"10\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"font-size: 10px; line-height: 10px;\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<table border=\"0\" width=\"200\" align=\"right\" cellpadding=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\tcellspacing=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"container590\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"hide\" height=\"45\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"font-size: 45px; line-height: 45px;\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td height=\"15\" style=\"font-size: 15px; line-height: 15px;\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td height=\"60\" style=\"font-size: 60px; line-height: 60px;\">&nbsp;</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<!-- end section -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
