/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2021-07-02 14:16:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/FinalProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/PrjApp/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1625098681000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("UTF-8");
	String cp = request.getContextPath();

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>Login</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400&display=swap\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("#iconchange\r\n");
      out.write("{\r\n");
      out.write("\tborder-radius: 15px !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<!-- 카카오 로그인 API -->\r\n");
      out.write("<script src=\"https://developers.kakao.com/sdk/js/kakao.min.js\">\r\n");
      out.write("\tKakao.init(\"a76949096713e82c75fa45bdb32ebb4c\");\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- 구글 로그인 API -->\r\n");
      out.write("<script src=\"https://apis.google.com/js/platform.js\" async defer></script>\r\n");
      out.write("<meta name=\"google-signin-client_id\" content=\"447693494839-5d859g9t2hvpdupbar05mii8a0c4ag1j.apps.googleusercontent.com\">\r\n");
      out.write("\r\n");
      out.write("<!-- 메일 전송 -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function send_mail(){\r\n");
      out.write("    window.open(\"./test_mail.jsp\", \"\", \"width=370, height=360, resizable=no, scrollbars=no, status=no\");\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"img js-fullheight\" style=\"background-image: url(images/jeju.png);\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<p class=\"userimg\">Romi 님의 사진입니다.&nbsp;&nbsp;&nbsp;</p>\r\n");
      out.write("<div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<section class=\"ftco-section\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row justify-content-center\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 text-center mb-5\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"heading-section\">로그인</h2>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row justify-content-center\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 col-lg-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"login-wrap p-0\">\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"mb-4\" style=\"text-align: right; font-size: 15px; font-family: 'Noto Sans KR', sans-serif;\" onclick=\"location.href='/PrjApp/Signin.jsp';\">계정이 없으신가요? 회원가입</h3>\r\n");
      out.write("\t\t\t\t\t\t<form action=\"#\" class=\"signin-form\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"이메일\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\trequired>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"password-field\" type=\"password\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"비밀번호\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span toggle=\"#password-field\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-fw fa-eye field-icon toggle-password\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"form-control btn btn-primary submit px-3\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"font-family: 'Noto Sans KR', sans-serif;\">로그인</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group d-md-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"w-50\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"checkbox-wrap checkbox-primary\" style=\"font-family: 'Noto Sans KR', sans-serif;\">자동 로그인<input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"checkbox\" checked> <span class=\"checkmark\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"w-50 text-md-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" style=\"color: #fff; font-family: 'Noto Sans KR', sans-serif;\" onclick=\"location.href='/PrjApp/FindPw.jsp';\">비밀번호 찾기</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t<br><p class=\"w-100 text-center\" style=\"font-family: 'Noto Sans KR', sans-serif; font-size: 15px;\">&mdash; SNS 계정으로 편하게 로그인하기 &mdash;</p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"social d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"width: 100px;\"><img src=\"images/kakao_login.png\" width=\"50px\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"width: 100px;\"><img src=\"images/naver_login.png\" width=\"50px\" style=\"border-radius: 5px;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"googlelogin g-signin2 iconchange\" data-width=\"50\" data-height=\"50\" data-onsuccess=\"onSignIn\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/popper.js\"></script>\r\n");
      out.write("\t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/main.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("        function onSignIn(googleUser) {\r\n");
      out.write("            // Useful data for your client-side scripts:\r\n");
      out.write("            var profile = googleUser.getBasicProfile();\r\n");
      out.write("            console.log(\"ID: \" + profile.getId()); // Don't send this directly to your server!\r\n");
      out.write("            console.log('Full Name: ' + profile.getName());\r\n");
      out.write("            console.log('Given Name: ' + profile.getGivenName());\r\n");
      out.write("            console.log('Family Name: ' + profile.getFamilyName());\r\n");
      out.write("            console.log(\"Image URL: \" + profile.getImageUrl());\r\n");
      out.write("            console.log(\"Email: \" + profile.getEmail());\r\n");
      out.write("\r\n");
      out.write("            // The ID token you need to pass to your backend:\r\n");
      out.write("            var id_token = googleUser.getAuthResponse().id_token;\r\n");
      out.write("            console.log(\"ID Token: \" + id_token);\r\n");
      out.write("        };\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
